name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
ignore-pr-updates: true
categories:
  - title: '🚀 Features'
    labels: [ 'feature' ]
  - title: '🐛 Bug Fixes'
    labels: [ 'bug' ]
