# Generated by Django 5.0.4 on 2024-04-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
    ]
